builders:
  hive_generator:
    import: "package:hive_generator/hive_generator.dart"
    builder_factories: ["getBuilder"]
    build_extensions: {".dart": [".hive.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]